USE master;
GO
IF NOT EXISTS
(
	SELECT * FROM sys.symmetric_keys WHERE symmetric_key_id = 101
)
CREATE MASTER KEY ENCRYPTION BY PASSWORD= '20120313'
GO
IF NOT EXISTS
(
	SELECT * FROM sys.certificates WHERE name = 'Cert'
)
CREATE CERTIFICATE MyCert
WITH SUBJECT = 'Cert';
GO
USE QLBongDa;
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE MyCert;
GO
ALTER DATABASE QLBongDa
SET ENCRYPTION ON;
GO

USE master;

BACKUP CERTIFICATE MyCert TO FILE = 'D:\certificate.cer'  
    WITH PRIVATE KEY ( FILE = 'D:\certificate.pvk' ,   
    ENCRYPTION BY PASSWORD = '20120313' );  
GO  

CREATE CERTIFICATE MyTDECert
FROM FILE = 'D:\certificate.cer'
WITH PRIVATE KEY (
FILE = 'D:\certificate.pvk',
DECRYPTION BY PASSWORD = '20120313')