USE QLBongDa
GO
-- BDAdmin
CREATE USER BDAdmin FOR LOGIN BDAdmin
GO
ALTER ROLE db_owner ADD MEMBER BDAdmin
GO
--BDBK
CREATE USER BDBK FOR LOGIN BDBK
GO
ALTER ROLE db_backupoperator ADD MEMBER BDBK
GO
--BDRead
CREATE USER BDRead FOR LOGIN BDRead
GO
ALTER ROLE db_datareader ADD MEMBER BDRead
GO
--BDU01 - Tao role db_create_table chi duoc cap quyen tao table cho BDU01
CREATE ROLE db_create_table AUTHORIZATION [dbo];
GRANT CREATE TABLE TO db_create_table;
GO
CREATE USER BDU01 FOR LOGIN BDU01;
GRANT ALTER ON SCHEMA::dbo TO BDU01;
GO
ALTER ROLE db_create_table ADD MEMBER BDU01;
GO
-- BDU02
CREATE USER BDU02 FOR LOGIN BDU02
GO
ALTER ROLE db_datawriter ADD MEMBER BDU02
GO
-- BDU03
CREATE USER BDU03 FOR LOGIN BDU03
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON [dbo].[CAULACBO] TO BDU03
GO
-- BDU04
CREATE USER BDU04 FOR LOGIN BDU04
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON [dbo].[CAUTHU] TO BDU04
DENY SELECT ON [dbo].[CAUTHU]([NGAYSINH]) TO BDU04
DENY UPDATE ON [dbo].[CAUTHU]([VITRI]) TO BDU04
GO
-- BDProfile
CREATE USER BDProfile FOR LOGIN BDProfile
GO
ALTER ROLE db_accessadmin ADD MEMBER BDProfile
GO



