/*----------------------------------------------------------
Nhom: 12
Ngay: 16/4/2023
----------------------------------------------------------*/
USE master
GO
IF DB_ID('QLSVNhom') IS NOT NULL
	DROP DATABASE QLSVNhom
GO
CREATE DATABASE QLSVNhom
GO
USE QLSVNhom
GO
-- Tạo bảng
CREATE TABLE SINHVIEN(
	MASV VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(100) NOT NULL,
	PRIMARY KEY(MASV)
	)
GO
CREATE TABLE NHANVIEN(
	MANV VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(100) NOT NULL,
	PUBKEY VARCHAR(20),
	PRIMARY KEY(MANV)
	)
GO
CREATE TABLE LOP(
	MALOP VARCHAR(20) NOT NULL,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),
	PRIMARY KEY(MALOP)
	)
GO
CREATE TABLE HOCPHAN(
	MAHP VARCHAR(20) NOT NULL,
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT,
	PRIMARY KEY(MAHP)
	)
GO
CREATE TABLE BANGDIEM(
	MASV VARCHAR(20) NOT NULL,
	MAHP VARCHAR(20) NOT NULL,
	DIEMTHI VARBINARY(MAX),
	PRIMARY KEY(MAHP,MASV)
	)
GO
-- TẠO KHOÁ NGOẠI
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP (MALOP);
GO
ALTER TABLE LOP ADD CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV);
GO
ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN (MASV);
GO
ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BANGDIEM_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN (MAHP);
GO

-- tạo PROCUREDURES
-- CAU I
IF OBJECT_ID('SP_INS_PUBLIC_NHANVIEN','P') IS NOT NULL
DROP PROCEDURE SP_INS_PUBLIC_NHANVIEN
GO
CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG INT,
	@TENDN NVARCHAR(100),
	@MATKHAU NVARCHAR(100)
AS
BEGIN
	-- TẠO KHOÁ ASYMMETRIC ĐỂ MÃ HOÁ MẬT KHẨU
	IF NOT EXISTS(SELECT * FROM sys.asymmetric_keys WHERE name = @MANV)
	BEGIN
		DECLARE @Sql NVARCHAR(MAX)
		SET @Sql = N'CREATE ASYMMETRIC KEY ' + QUOTENAME(@MANV) + N'
		WITH ALGORITHM = RSA_2048 
		ENCRYPTION BY PASSWORD = ''' + @MATKHAU + N''';'
		EXEC sp_executesql @Sql;
	END
	DECLARE @LUONG_VARBINARY VARBINARY(MAX) = CONVERT(VARBINARY(MAX), @LUONG)
    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU,PUBKEY)
    VALUES (@MANV, @HOTEN, @EMAIL, ENCRYPTBYASYMKEY(ASYMKEY_ID(@MANV), @LUONG_VARBINARY), @TENDN, HASHBYTES('SHA1', @MATKHAU),@MANV);
END
go
-- ii
IF OBJECT_ID('SP_SEL_PUBLIC_NHANVIEN','P') IS NOT NULL
DROP PROCEDURE SP_SEL_PUBLIC_NHANVIEN
GO
CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN
	@MANV NVARCHAR(100),
	@MATKHAU NVARCHAR(100)
AS
BEGIN
	SELECT NV.MANV, NV.HOTEN, NV.EMAIL,CONVERT(INT, DECRYPTBYASYMKEY(ASYMKEY_ID(NV.MANV),NV.LUONG, @MATKHAU)) as LUONGCB
	FROM NHANVIEN AS NV
	where nv.TENDN = @MANV and NV.MATKHAU =  HASHBYTES('SHA1', @MATKHAU)
END
GO 
--exec SP_SEL_PUBLIC_NHANVIEN 'NVA', '123456'
--exec SP_SEL_PUBLIC_NHANVIEN 'NVB', '1234567'
-- THÊM DỮ LIỆU MẪU
EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'nva@yahoo.com', 3000000,'NVA', '123456'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV02', 'NGUYEN VAN B', 'nvb@yahoo.com', 2000000,'NVB', '1234567'

INSERT INTO LOP(MALOP,TENLOP,MANV)
VALUES 
	('L01', N'Công nghệ thông tin K20','NV01'),
	('L02', N'Công nghệ thông tin K21','NV02')
GO

INSERT INTO HOCPHAN(MAHP,TENHP,SOTC)
VALUES 
	('HP01', N'Nhập môn mã hoá mật mã',4),
	('HP02', N'Mã hoá cơ sở dữ liệu',4)
GO

INSERT INTO SINHVIEN(MASV,HOTEN,NGAYSINH,DIACHI,MALOP,TENDN,MATKHAU)
VALUES 
	('SV01', N'Trần Văn C','2002-01-01', N'280 AN DUONG VUONG', 'L01', N'SVC', HASHBYTES('SHA1',N'abcde')),
	('SV02', N'Trần Văn D','2002-01-01', N'280 TO VINH DIEN', 'L01', N'SVD', HASHBYTES('SHA1',N'abcdef'))
GO

-- Bảng DIEM sẽ tạo procedure để nhập vào

-- Chức năng login
IF OBJECT_ID('LOG_IN','P') IS NOT NULL
DROP PROCEDURE LOG_IN
GO
CREATE PROCEDURE LOG_IN
	@MANV NVARCHAR(100),
	@MATKHAU NVARCHAR(100)
AS
BEGIN
	SELECT NV.MANV, NV.TENDN,SUBSTRING(NV.MANV, 1, 2) AS CHUCNANG
	FROM NHANVIEN AS NV
	where nv.TENDN = @MANV and NV.MATKHAU =  HASHBYTES('SHA1', @MATKHAU)
	UNION
	SELECT sv.MASV, SV.TENDN, SUBSTRING(sv.MASV, 0, 2) AS CHUCNANG
	FROM SINHVIEN AS sv
	where sv.TENDN = @MANV and sv.MATKHAU =  HASHBYTES('SHA1', @MATKHAU)
END
GO 
--exec LOG_IN 'NVB', '1234567'

-- Quản lý lớp học
--Stored procedure xóa lớp học
go
IF OBJECT_ID('SP_DELETE_CLASS','P') IS NOT NULL
DROP PROCEDURE SP_DELETE_CLASS
GO
CREATE PROCEDURE SP_DELETE_CLASS(
	@MALOP VARCHAR(20),
	@TENLOP NVARCHAR(100),
	@MANV VARCHAR(20)
	)
AS
BEGIN
	if (select COUNT(*) from LOP where MALOP=@MALOP and TENLOP=@TENLOP and MANV=@MANV)>0 
	begin
	update SINHVIEN set MALOP=null where MALOP= @MALOP
	delete LOP where MALOP=@MALOP
	end
	else
	print('Error')
END
-- Quản lý học sinh
-- Kiem tra nhan vien co quan ly sinh vien
IF OBJECT_ID('NHAN_VIEN_QL_SINH_VIEN','P') IS NOT NULL
DROP PROCEDURE NHAN_VIEN_QL_SINH_VIEN
GO
CREATE PROCEDURE NHAN_VIEN_QL_SINH_VIEN
	@MANV VARCHAR(20),
	@MASV VARCHAR(20)
AS
BEGIN
	SELECT *
	FROM SINHVIEN as sv
	INNER JOIN lop ON sv.MALOP = lop.MALOP
	INNER JOIN NHANVIEN as nv ON lop.MANV = nv.MANV
	where sv.MASV = @MASV and nv.MANV = @MANV
END
GO
-- Cập nhật thong tin sinh viên
IF OBJECT_ID('CAP_NHAT_SINH_VIEN','P') IS NOT NULL
DROP PROCEDURE CAP_NHAT_SINH_VIEN
GO
CREATE PROCEDURE CAP_NHAT_SINH_VIEN
	@MASV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20)
AS
BEGIN
	UPDATE SINHVIEN
	SET MASV=@MASV,HOTEN=@HOTEN,NGAYSINH=@NGAYSINH,DIACHI=@DIACHI,MALOP=@MALOP
	WHERE MASV = @MASV;
END
GO
--exec CAP_NHAT_SINH_VIEN 'SV01', N'Trần Văn C','2002-01-01', N'280 AN DUONG VUONG', 'L01'

--Nhap diem
IF OBJECT_ID('Nhap_Diem','P') IS NOT NULL
DROP PROCEDURE Nhap_Diem
GO
CREATE PROCEDURE Nhap_Diem
	@MASV VARCHAR(20),
	@MAHP VARCHAR(20),
	@DIEMTHI VARCHAR(20),
	@MANV VARCHAR(20)
AS
BEGIN
	INSERT INTO BANGDIEM(MASV, MAHP, DIEMTHI)
    VALUES (@MASV, @MAHP,ENCRYPTBYASYMKEY(ASYMKEY_ID(@MANV), @DIEMTHI))
END
GO

Exec Nhap_Diem 'SV02', 'HP01','2','NV01'
select * from BANGDIEM
